version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: 'always'
    ports:
      - '3307:3306'
    networks:
      - app-tier

    # environment:
    #   MYSQL_ROOT_HOST: '%'
    #   MYSQL_ROOT_PASSWORD: 'rootpassword'
    #   MYSQL_DATABASE: 'skillzen'
    #   MYSQL_USER: 'dbuser'
    #   MYSQL_PASSWORD: 'dbpassword'
    env_file:
      - docker.env

  web:
    image: bhargavgohil/skillzen:1
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node dist/main'
    ports:
      - '8800:8800'
    networks:
      - app-tier
