version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: 'always'
    ports:
      - '3307:3306'
    networks:
      - app-tier

    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - docker.env

  web:
    image: bhargavgohil/skilzen:1.1
    depends_on:
      - db
    # added command because the db container was not running when the web container was started
    # so added the delay to wait for the db container to start 
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node dist/main'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    ports:
      - '8800:8800'
    networks:
      - app-tier
volumes:
  db-data: